import Head from 'next/head'
import { useKeenSlider } from 'keen-slider/react'
import 'keen-slider/keen-slider.min.css'

import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillGithub, AiFillLinkedin } from 'react-icons/ai'

import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import code from '../public/code.png'
import advicegenerator from '../public/advicegenerator.png'
import caravan from '../public/caravan.png'
import NLW from '../public/NLW e-sports.png'
import todoappReact from '../public/todoappReact.png'
import TextSpeech from '../public/Text-Speech.png'
import qrcode from '../public/qrcode generator.png'
import ecommerce from '../public/e-commercejquery.png'
import introsection from '../public/introsection.png'
import interactiveC from '../public/interactiveC.png'
import wildbeast from '../public/wildbeast.png'

import { useState, useEffect } from 'react'

function ThumbnailPlugin(mainRef) {
  return slider => {
    function removeActive() {
      slider.slides.forEach(slide => {
        slide.classList.remove('active')
      })
    }
    function addActive(idx) {
      slider.slides[idx].classList.add('active')
    }

    function addClickEvents() {
      slider.slides.forEach((slide, idx) => {
        slide.addEventListener('click', () => {
          if (mainRef.current) mainRef.current.moveToIdx(idx)
        })
      })
    }

    slider.on('created', () => {
      if (!mainRef.current) return
      addActive(slider.track.details.rel)
      addClickEvents()
      mainRef.current.on('animationStarted', main => {
        removeActive()
        const next = main.animator.targetIdx || 0
        addActive(main.track.absToRel(next))
        slider.moveToIdx(Math.min(slider.track.details.maxIdx, next))
      })
    })
  }
}

export default function Home() {
  const [darkMode, setDarkMode] = useState(true)
  const [sliderRef, instanceRef] = useKeenSlider({
    initial: 0
  })
  const [thumbnailRef] = useKeenSlider(
    {
      initial: 0,
      slides: {
        perView: 4,
        spacing: 10
      }
    },
    [ThumbnailPlugin(instanceRef)]
  )
  useEffect(() => {
    const key = Object.keys(localStorage)
    if (key.includes('theme')) {
      setDarkMode(JSON.parse(localStorage.getItem('theme')))
    }
  }, [])

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons">SE Leonardo</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => {
                    window.localStorage.setItem('theme', !darkMode)
                    setDarkMode(JSON.parse(localStorage.getItem('theme')))
                  }}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  href="https://drive.google.com/file/d/1aWwubNFxswb77chC_XdAqVFUsVe_yL4A/view"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Leonardo de Lima
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Front-end Software Engineer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200">
              Hello, I'm Front-end SE. Browse my page to see more about me and
              my projects!
            </p>
          </div>
          <div className="text-5xl flex  justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a
              href="https://github.com/LeonardoLimaSilveira"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillGithub className="cursor-pointer" />
            </a>
            <a
              href="https://www.linkedin.com/in/leonardo-lima-42596b235/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillLinkedin className="cursor-pointer" />
            </a>
          </div>
          <div className="relative mx-auto  bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 ">
            <Image
              alt="image description"
              src={deved}
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>
        <section>
          <div className=" ">
            <div className="text-center flex justify-center items-center flex-col shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image alt="image description" src={code} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Experience
              </h3>
              <p className="py-2 dark:text-gray-200">
                Beginner Front-end SE with knowledge in HTML, CSS, JS, REACTJS,
                REACT ROUTER, JQUERY, GIT, TAILWINDCSS, BOOTSTRAP, TYPESCRIPT,
                STYLED-COMPONENTS
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-200">
                I seek to use all my knowledge for the benefit of the company
                and collaborators, always trying to be evolving and updated what
                our customers need.
              </p>
            </div>
          </div>
        </section>
        <section className="">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portifólio</h3>
            <p className="dark:text-white my-2">
              Down below are some of my projects
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap  ">
            <div ref={sliderRef} className="keen-slider">
              <div className="keen-slider__slide number-slide1">
                <a
                  href="https://todoappfacebook-o5fp15bss-leonardolimasilveira.vercel.app"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    alt="image description"
                    src={todoappReact}
                    className="rounded-lg object-cover"
                    width={'100%'}
                    height={'100%'}
                    layout="responsive"
                  />
                </a>
              </div>
              <div className="keen-slider__slide number-slide2">
                <div className="cursor-pointer">
                  <a
                    href="https://leonardolimasilveira.github.io/Caravan-bootstap"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <Image
                      alt="image description"
                      src={caravan}
                      className="rounded-lg object-cover"
                      width={'100%'}
                      height={'100%'}
                      layout="responsive"
                    />
                  </a>
                </div>
              </div>
              <div className="keen-slider__slide number-slide3">
                <div className="basis-1/4 flex-1 cursor-pointer">
                  <a
                    href="https://interactivecardreact-p2k54mngl-leonardolimasilveira.vercel.app"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <Image
                      alt="image description"
                      src={interactiveC}
                      className="rounded-lg object-cover"
                      width={'100%'}
                      height={'100%'}
                      layout="responsive"
                    />
                  </a>
                </div>
              </div>
              <div className="keen-slider__slide number-slide4">
                <div className="basis-1/4 flex-1 cursor-pointer">
                  <a
                    href="https://leonardolimasilveira.github.io/E-commerceByLeonardoLS"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <Image
                      alt="image description"
                      src={ecommerce}
                      className="rounded-lg object-cover"
                      width={'100%'}
                      height={'100%'}
                      layout="responsive"
                    />
                  </a>
                </div>
              </div>
              <div className="keen-slider__slide number-slide5">
                <a
                  href="https://github.com/LeonardoLimaSilveira/e-Sports"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    alt="image description"
                    src={NLW}
                    className="rounded-lg object-cover"
                    width={'100%'}
                    height={'100%'}
                    layout="responsive"
                  />
                </a>
              </div>
              <div className="keen-slider__slide number-slide6">
                <a
                  href="https://leonardolimasilveira.github.io/QRCODEGenerator/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    alt="image description"
                    src={qrcode}
                    className="rounded-lg object-cover"
                    width={'100%'}
                    height={'100%'}
                    layout="responsive"
                  />
                </a>
              </div>
              <div className="keen-slider__slide number-slide7">
                <a
                  href="https://leonardolimasilveira.github.io/Text-speech"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    alt="image description"
                    src={TextSpeech}
                    className="rounded-lg object-cover"
                    width={'100%'}
                    height={'100%'}
                    layout="responsive"
                  />
                </a>
              </div>
              <div className="keen-slider__slide number-slide8">
                <a
                  href="https://introsec-mo0wu4ves-leonardolimasilveira.vercel.app"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    alt="image description"
                    src={introsection}
                    className="rounded-lg object-cover"
                    width={'100%'}
                    height={'100%'}
                    layout="responsive"
                  />
                </a>
              </div>
              <div className="keen-slider__slide number-slide9">
                <a
                  href="https://leonardolimasilveira.github.io/AdviceGenerator"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    alt="image description"
                    src={advicegenerator}
                    className="rounded-lg object-cover"
                    width={'100%'}
                    height={'100%'}
                    layout="responsive"
                  />
                </a>
              </div>
              <div className="keen-slider__slide number-slide10">
                <a
                  href="https://leonardolimasilveira.github.io/wildbeast"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    alt="image description"
                    src={wildbeast}
                    className="rounded-lg object-cover"
                    width={'100%'}
                    height={'100%'}
                    layout="responsive"
                  />
                </a>
              </div>
            </div>
          </div>

          <div ref={thumbnailRef} className="keen-slider thumbnail">
            <div className="keen-slider__slide number-slide1">
              <Image alt="image desc" src={todoappReact} />
            </div>
            <div className="keen-slider__slide number-slide2">
              <Image alt="image desc" src={caravan} />
            </div>
            <div className="keen-slider__slide number-slide3">
              <Image alt="image desc" src={interactiveC} />
            </div>
            <div className="keen-slider__slide number-slide4">
              <Image alt="image desc" src={ecommerce} />
            </div>
            <div className="keen-slider__slide number-slide5">
              <Image alt="image desc" src={NLW} />
            </div>
            <div className="keen-slider__slide number-slide6">
              <Image alt="image desc" src={qrcode} />
            </div>
            <div className="keen-slider__slide number-slide7">
              <Image alt="image desc" src={TextSpeech} />
            </div>
            <div className="keen-slider__slide number-slide8">
              <Image alt="image desc" src={introsection} />
            </div>
            <div className="keen-slider__slide number-slide9">
              <Image alt="image desc" src={advicegenerator} />
            </div>
            <div className="keen-slider__slide number-slide10">
              <Image alt="image desc" src={wildbeast} />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
